/**
 * Class stores lists of choices to shift into with their name and size
 */
export class MorphinOptions {

}

MorphinOptions.animal = [
    { name: 'Blue Whale', size: 'col' },
    { name: 'Diplodocus', size: 'col' },
    { name: 'Giganotosaurus', size: 'col' },
    { name: 'Great White Whale', size: 'col' },
    { name: 'Immense Tortoise', size: 'col' },
    { name: 'Titanoboa', size: 'col' },
    { name: 'Bat', size: 'dim' },
    { name: 'Snark', size: 'dim' },
    { name: 'Toad', size: 'dim' },
    { name: 'Angustiden', size: 'grg' },
    { name: 'Basilosaurus', size: 'grg' },
    { name: 'Brachiosaurus', size: 'grg' },
    { name: 'Crimson Whale', size: 'grg' },
    { name: 'Deinosuchus', size: 'grg' },
    { name: 'Dire Crocodile', size: 'grg' },
    { name: 'Dire Shark (Megalodon)', size: 'grg' },
    { name: 'Emperor Walrus', size: 'grg' },
    { name: 'Giant Anaconda', size: 'grg' },
    { name: 'Giant Snapping Turtle', size: 'grg' },
    { name: 'Kronosaurus', size: 'grg' },
    { name: 'Megaprimatus', size: 'grg' },
    { name: 'Roc', size: 'grg' },
    { name: 'Spinosaurus', size: 'grg' },
    { name: 'Therizinosaurus', size: 'grg' },
    { name: 'Tylosaurus', size: 'grg' },
    { name: 'Tyrannosaurus', size: 'grg' },
    { name: 'Whale', size: 'grg' },
    { name: 'Zeuglodon', size: 'grg' },
    { name: 'Allosaurus', size: 'huge' },
    { name: 'Amargasaurus', size: 'huge' },
    { name: 'Ankylosaurus', size: 'huge' },
    { name: 'Archelon', size: 'huge' },
    { name: 'Baluchitherium', size: 'huge' },
    { name: 'Behemoth Hippopotamus', size: 'huge' },
    { name: 'Brontotherium', size: 'huge' },
    { name: 'Cameroceras', size: 'huge' },
    { name: 'Deinotherium', size: 'huge' },
    { name: 'Devil Monkey', size: 'huge' },
    { name: 'Dunkleosteus', size: 'huge' },
    { name: 'Elasmosaurus', size: 'huge' },
    { name: 'Elasmotherium', size: 'huge' },
    { name: 'Elephant', size: 'huge' },
    { name: 'Frog Father', size: 'huge' },
    { name: 'Giant Gar', size: 'huge' },
    { name: 'Giant Squid', size: 'huge' },
    { name: 'Giraffe', size: 'huge' },
    { name: 'Great White Shark', size: 'huge' },
    { name: 'Iguanodon', size: 'huge' },
    { name: 'Kaprosuchus', size: 'huge' },
    { name: 'Killer Seahorse', size: 'huge' },
    { name: 'Mastodon Elephant', size: 'huge' },
    { name: 'Megalania', size: 'huge' },
    { name: 'Megatherium', size: 'huge' },
    { name: 'Mokele-Mbembe', size: 'huge' },
    { name: 'Orca', size: 'huge' },
    { name: 'Parasaurolophus', size: 'huge' },
    { name: 'Quetzalcoatlus', size: 'huge' },
    { name: 'Saltwater Crocodile', size: 'huge' },
    { name: 'Stegosaurus', size: 'huge' },
    { name: 'Triceratops', size: 'huge' },
    { name: 'Yolubilis Heron', size: 'huge' },
    { name: 'Arsinoitherium', size: 'lg' },
    { name: 'Aurochs', size: 'lg' },
    { name: 'Axe Beak', size: 'lg' },
    { name: 'Bison', size: 'lg' },
    { name: 'Camel', size: 'lg' },
    { name: 'Ceratosaurus', size: 'lg' },
    { name: 'Chalicotherium', size: 'lg' },
    { name: 'Crocodile', size: 'lg' },
    { name: 'Dimetrodon', size: 'lg' },
    { name: 'Dire Ape', size: 'lg' },
    { name: 'Dire Bat', size: 'lg' },
    { name: 'Dire Bear', size: 'lg' },
    { name: 'Dire Boar', size: 'lg' },
    { name: 'Dire Hyena', size: 'lg' },
    { name: 'Dire Lion', size: 'lg' },
    { name: 'Dire Polar Bear', size: 'lg' },
    { name: 'Dire Tiger', size: 'lg' },
    { name: 'Dire Weasel', size: 'lg' },
    { name: 'Dire Wolf', size: 'lg' },
    { name: 'Dire Wolverine', size: 'lg' },
    { name: 'Embolotherium', size: 'lg' },
    { name: 'Emperor Cobra', size: 'lg' },
    { name: 'Enchanter Heron', size: 'lg' },
    { name: 'Gallerok', size: 'lg' },
    { name: 'Giant Blowfish', size: 'lg' },
    { name: 'Giant Chameleon', size: 'lg' },
    { name: 'Giant Frilled Lizard', size: 'lg' },
    { name: 'Giant Moray Eel', size: 'lg' },
    { name: 'Giant Octopus', size: 'lg' },
    { name: 'Giant Seahorse', size: 'lg' },
    { name: 'Giant Skunk', size: 'lg' },
    { name: 'Giant Toad', size: 'lg' },
    { name: 'Giant Vulture', size: 'lg' },
    { name: 'Gliding Turtle', size: 'lg' },
    { name: 'Goliath Frog', size: 'lg' },
    { name: 'Gorilla', size: 'lg' },
    { name: 'Grizzly Bear', size: 'lg' },
    { name: 'Gylptodon', size: 'lg' },
    { name: 'Hammerhead Shark', size: 'lg' },
    { name: 'Helicoprion', size: 'lg' },
    { name: 'Hippopotamus', size: 'lg' },
    { name: 'Horse', size: 'lg' },
    { name: 'Impaler Shrike', size: 'lg' },
    { name: 'Kentrosaurus', size: 'lg' },
    { name: 'Lion', size: 'lg' },
    { name: 'Manta Ray', size: 'lg' },
    { name: 'Marax', size: 'lg' },
    { name: 'Marine Crocodile', size: 'lg' },
    { name: 'Megaloceros', size: 'lg' },
    { name: 'Moa', size: 'lg' },
    { name: 'Narwhal', size: 'lg' },
    { name: 'Nothosaur', size: 'lg' },
    { name: 'Pachycephalosaurus', size: 'lg' },
    { name: 'Plesiosaurus', size: 'lg' },
    { name: 'Polar Bear', size: 'lg' },
    { name: 'Pteranodon', size: 'lg' },
    { name: 'Rhinoceros', size: 'lg' },
    { name: 'River Elk', size: 'lg' },
    { name: 'Shark', size: 'lg' },
    { name: 'Stygian Hot-Blooded Horse', size: 'lg' },
    { name: 'Styracosaurus', size: 'lg' },
    { name: 'Swordfish', size: 'lg' },
    { name: 'Tiger', size: 'lg' },
    { name: 'Uintatherium', size: 'lg' },
    { name: 'Walrus', size: 'lg' },
    { name: 'Wolliped', size: 'lg' },
    { name: 'Woolly Rhinoceros', size: 'lg' },
    { name: 'Black Bear', size: 'med' },
    { name: 'Boar', size: 'med' },
    { name: 'Brush Thylacine', size: 'med' },
    { name: 'Bull Shark', size: 'med' },
    { name: 'Cheetah', size: 'med' },
    { name: 'Chelish Hell-Bred Dog', size: 'med' },
    { name: 'Constrictor Snake', size: 'med' },
    { name: 'Deinonychus', size: 'med' },
    { name: 'Digmaul', size: 'med' },
    { name: 'Dimorphodon', size: 'med' },
    { name: 'Dire Badger', size: 'med' },
    { name: 'Dolphin', size: 'med' },
    { name: 'Elk', size: 'med' },
    { name: 'Faerie Mount', size: 'med' },
    { name: 'Gar', size: 'med' },
    { name: 'Giant Frog', size: 'med' },
    { name: 'Giant Gecko', size: 'med' },
    { name: 'Giant Owl', size: 'med' },
    { name: 'Giant Porcupine', size: 'med' },
    { name: 'Giant Raven', size: 'med' },
    { name: 'Giant Stargazer', size: 'med' },
    { name: 'Giant Tortoise', size: 'med' },
    { name: 'Giant Weasel', size: 'med' },
    { name: 'Goblin Dog', size: 'med' },
    { name: 'Hobbe Hound', size: 'med' },
    { name: 'Hyena', size: 'med' },
    { name: 'Jigsaw Shark', size: 'med' },
    { name: 'Kangaroo', size: 'med' },
    { name: 'Leopard', size: 'med' },
    { name: 'Mindspin Ram', size: 'med' },
    { name: 'Mome Rath', size: 'med' },
    { name: 'Monitor Lizard', size: 'med' },
    { name: 'Pony', size: 'med' },
    { name: 'Ram', size: 'med' },
    { name: 'Riding Dog', size: 'med' },
    { name: 'Ringhorn', size: 'med' },
    { name: 'Sea Crawler', size: 'med' },
    { name: 'Squid', size: 'med' },
    { name: 'Stag', size: 'med' },
    { name: 'Stingray', size: 'med' },
    { name: 'Tiger Fish', size: 'med' },
    { name: 'Timber Wolf', size: 'med' },
    { name: 'Troodon', size: 'med' },
    { name: 'Venomous Snake', size: 'med' },
    { name: 'Wolf', size: 'med' },
    { name: 'Wolverine', size: 'med' },
    { name: 'Antelope', size: 'sm' },
    { name: 'Baboon', size: 'sm' },
    { name: 'Badger', size: 'sm' },
    { name: 'Blackwisp Egret', size: 'sm' },
    { name: 'Dallo', size: 'sm' },
    { name: 'Dire Rat', size: 'sm' },
    { name: 'Dodo', size: 'sm' },
    { name: 'Dog', size: 'sm' },
    { name: 'Dwarf Caiman', size: 'sm' },
    { name: 'Eagle', size: 'sm' },
    { name: 'Electric Eel', size: 'sm' },
    { name: 'Falcon', size: 'sm' },
    { name: 'Goat', size: 'sm' },
    { name: 'Great Horned Owl', size: 'sm' },
    { name: 'Octopus', size: 'sm' },
    { name: 'Peafowl', size: 'sm' },
    { name: 'Penguin', size: 'sm' },
    { name: 'Pig', size: 'sm' },
    { name: 'Pilo', size: 'sm' },
    { name: 'Quillcat', size: 'sm' },
    { name: 'Seal', size: 'sm' },
    { name: 'Skittergoat', size: 'sm' },
    { name: 'Sorico', size: 'sm' },
    { name: 'Switchback Jackal', size: 'sm' },
    { name: 'Thylacine', size: 'sm' },
    { name: 'Trumpeter Swan', size: 'sm' },
    { name: 'Velociraptor', size: 'sm' },
    { name: 'Vulture', size: 'sm' },
    { name: 'Archaeopteryx', size: 'tiny' },
    { name: 'Cat', size: 'tiny' },
    { name: 'Chicken', size: 'tiny' },
    { name: 'Compsognathus', size: 'tiny' },
    { name: 'Flying Fox', size: 'tiny' },
    { name: 'Flying Squirrel', size: 'tiny' },
    { name: 'Fox', size: 'tiny' },
    { name: 'Hawk', size: 'tiny' },
    { name: 'Lich Newt', size: 'tiny' },
    { name: 'Lizard', size: 'tiny' },
    { name: 'Monkey', size: 'tiny' },
    { name: 'Otter', size: 'tiny' },
    { name: 'Owl', size: 'tiny' },
    { name: 'Petromin', size: 'tiny' },
    { name: 'Poison Frog', size: 'tiny' },
    { name: 'Porcupine', size: 'tiny' },
    { name: 'Raccoon', size: 'tiny' },
    { name: 'Rat', size: 'tiny' },
    { name: 'Raven', size: 'tiny' },
    { name: 'Red Panda', size: 'tiny' },
    { name: 'Rhamphorhynchus', size: 'tiny' },
    { name: 'Rock Tuatara', size: 'tiny' },
    { name: 'Skunk', size: 'tiny' },
    { name: 'Sloth', size: 'tiny' },
    { name: 'Snapping Turtle', size: 'tiny' },
    { name: 'Tuatara', size: 'tiny' },
    { name: 'Tullimonstrum', size: 'tiny' },
    { name: 'Varisian Hagfish', size: 'tiny' },
    { name: 'Viper', size: 'tiny' },
    { name: 'Weasel', size: 'tiny' }
];

MorphinOptions.elemental = [
    { name: 'Huge Air Elemental', size: 'huge' },
    { name: 'Huge Earth Elemental', size: 'huge' },
    { name: 'Huge Fire Elemental', size: 'huge' },
    { name: 'Huge Water Elemental', size: 'huge' },
    { name: 'Large Air Elemental', size: 'lg' },
    { name: 'Large Earth Elemental', size: 'lg' },
    { name: 'Large Fire Elemental', size: 'lg' },
    { name: 'Large Water Elemental', size: 'lg' },
    { name: 'Medium Air Elemental', size: 'med' },
    { name: 'Medium Earth Elemental', size: 'med' },
    { name: 'Medium Fire Elemental', size: 'med' },
    { name: 'Medium Water Elemental', size: 'med' },
    { name: 'Small Air Elemental', size: 'sm' },
    { name: 'Small Earth Elemental', size: 'sm' },
    { name: 'Small Fire Elemental', size: 'sm' },
    { name: 'Small Water Elemental', size: 'sm' }
];

MorphinOptions.plant = [
    { name: 'Cauldron Bloom', size: 'col' },
    { name: 'Mu Spore', size: 'col' },
    { name: 'Sard', size: 'col' },
    { name: 'Tarantula Tree', size: 'col' },
    { name: 'Zygomind', size: 'col' },
    { name: 'Blood Algae Swarm', size: 'dim' },
    { name: 'Vireseed Swarm', size: 'fine' },
    { name: 'Barometz', size: 'grg' },
    { name: 'Bodythief', size: 'grg' },
    { name: 'Irminsul', size: 'grg' },
    { name: 'Lotus Tree', size: 'grg' },
    { name: 'Xhamen-Dor', size: 'grg' },
    { name: 'Zomok', size: 'grg' },
    { name: 'Bloodplate Burster', size: 'huge' },
    { name: 'Bramble Throne', size: 'huge' },
    { name: 'Canopy Creeper', size: 'huge' },
    { name: 'Corpse Lotus', size: 'huge' },
    { name: 'Giant Devil\'s Tooth', size: 'huge' },
    { name: 'Giant Flytrap', size: 'huge' },
    { name: 'Giant Sundew', size: 'huge' },
    { name: 'Hangman Tree', size: 'huge' },
    { name: 'Heartrot Tree', size: 'huge' },
    { name: 'Jinmenju', size: 'huge' },
    { name: 'Kapre', size: 'huge' },
    { name: 'Moonflower', size: 'huge' },
    { name: 'Pixie Circle', size: 'huge' },
    { name: 'Quickwood', size: 'huge' },
    { name: 'Tendriculos', size: 'huge' },
    { name: 'Treant', size: 'huge' },
    { name: 'Umdhlebi', size: 'huge' },
    { name: 'Alraune', size: 'lg' },
    { name: 'Ascomoid', size: 'lg' },
    { name: 'Assassin Vine', size: 'lg' },
    { name: 'Blood Bramble', size: 'lg' },
    { name: 'Blood Lily', size: 'lg' },
    { name: 'Bonewrought Willow', size: 'lg' },
    { name: 'Brambleblight', size: 'lg' },
    { name: 'Carrion Creeper', size: 'lg' },
    { name: 'Crypt Flower', size: 'lg' },
    { name: 'Kudimmu', size: 'lg' },
    { name: 'Lythirium', size: 'lg' },
    { name: 'Mosslord', size: 'lg' },
    { name: 'Sargassum Fiend', size: 'lg' },
    { name: 'Shambling Mound', size: 'lg' },
    { name: 'Stranglereed', size: 'lg' },
    { name: 'Sump Steward', size: 'lg' },
    { name: 'Viper Vine', size: 'lg' },
    { name: 'Basidirond', size: 'med' },
    { name: 'Blood Maize', size: 'med' },
    { name: 'Bonethorn', size: 'med' },
    { name: 'Boruta', size: 'med' },
    { name: 'Bramblelash', size: 'med' },
    { name: 'Cerebric Fungus', size: 'med' },
    { name: 'Frost Fir', size: 'med' },
    { name: 'Fungal Nymph', size: 'med' },
    { name: 'Fungus Queen', size: 'med' },
    { name: 'Gluttongrass', size: 'med' },
    { name: 'Jack-O\'-Lantern', size: 'med' },
    { name: 'Living Topiary', size: 'med' },
    { name: 'Melfesh Monster', size: 'med' },
    { name: 'Mi-Go', size: 'med' },
    { name: 'Myceloid', size: 'med' },
    { name: 'Phantom Fungus', size: 'med' },
    { name: 'Psychepore', size: 'med' },
    { name: 'Saguaroi', size: 'med' },
    { name: 'Violet Fungus', size: 'med' },
    { name: 'Weedwhip', size: 'med' },
    { name: 'Yellow Musk Creeper', size: 'med' },
    { name: 'Cactus Leshy', size: 'sm' },
    { name: 'Calathgar', size: 'sm' },
    { name: 'Fuldrex', size: 'sm' },
    { name: 'Fungus Leshy', size: 'sm' },
    { name: 'Gourd Leshy', size: 'sm' },
    { name: 'Kawa Akago', size: 'sm' },
    { name: 'Leaf Leshy', size: 'sm' },
    { name: 'Leaf Ray', size: 'sm' },
    { name: 'Lichen Leshy', size: 'sm' },
    { name: 'Lotus Leshy', size: 'sm' },
    { name: 'Mandragora', size: 'sm' },
    { name: 'Mindslaver Mold', size: 'sm' },
    { name: 'Mire Nettle', size: 'sm' },
    { name: 'Moldwretch', size: 'sm' },
    { name: 'Nulmind', size: 'sm' },
    { name: 'Phycomid', size: 'sm' },
    { name: 'Seaweed Leshy', size: 'sm' },
    { name: 'Sunflower Leshy', size: 'sm' },
    { name: 'Tsaalgrend', size: 'sm' },
    { name: 'Vegepygmy', size: 'sm' },
    { name: 'Xtabay', size: 'sm' },
    { name: 'Griefgall', size: 'tiny' }
];

MorphinOptions.monstrousHumanoid = [
    { name: 'Humbaba', size: 'col' },
    { name: 'Ningen', size: 'col' },
    { name: 'Elder Deep One', size: 'grg' },
    { name: 'Ithaqua', size: 'grg' },
    { name: 'Basavan', size: 'huge' },
    { name: 'Gegenees', size: 'huge' },
    { name: 'Saurian', size: 'huge' },
    { name: 'Thriae Queen', size: 'huge' },
    { name: 'Annis Hag', size: 'lg' },
    { name: 'Anunnaki', size: 'lg' },
    { name: 'Buggane', size: 'lg' },
    { name: 'Centaur', size: 'lg' },
    { name: 'Derhii', size: 'lg' },
    { name: 'Fen Mauler', size: 'lg' },
    { name: 'Girtablilu', size: 'lg' },
    { name: 'Ichthyocentaur', size: 'lg' },
    { name: 'Karkinoi', size: 'lg' },
    { name: 'Krampus', size: 'lg' },
    { name: 'Lamia', size: 'lg' },
    { name: 'Lamia Matriarch', size: 'lg' },
    { name: 'Minotaur', size: 'lg' },
    { name: 'Nependis', size: 'lg' },
    { name: 'Paguroida', size: 'lg' },
    { name: 'Saumen Kar', size: 'lg' },
    { name: 'Shobhad', size: 'lg' },
    { name: 'Stormghost', size: 'lg' },
    { name: 'Tikbalang', size: 'lg' },
    { name: 'Vouivre', size: 'lg' },
    { name: 'Yeti', size: 'lg' },
    { name: 'Yig', size: 'lg' },
    { name: 'Adaro', size: 'med' },
    { name: 'Adherer', size: 'med' },
    { name: 'Blood Hag', size: 'med' },
    { name: 'Cecaelia', size: 'med' },
    { name: 'Ceratioidi', size: 'med' },
    { name: 'Contemplative', size: 'med' },
    { name: 'Deathsnatcher', size: 'med' },
    { name: 'Deep One', size: 'med' },
    { name: 'Dire Corby', size: 'med' },
    { name: 'Doppelganger', size: 'med' },
    { name: 'Euryale', size: 'med' },
    { name: 'Four-Armed Sahuagin', size: 'med' },
    { name: 'Gargoyle', size: 'med' },
    { name: 'Ghole', size: 'med' },
    { name: 'Graeae', size: 'med' },
    { name: 'Green Hag', size: 'med' },
    { name: 'Grioth', size: 'med' },
    { name: 'Harpy', size: 'med' },
    { name: 'Herne', size: 'med' },
    { name: 'Jorogumo', size: 'med' },
    { name: 'Kech', size: 'med' },
    { name: 'Maenad', size: 'med' },
    { name: 'Maftet', size: 'med' },
    { name: 'Malenti', size: 'med' },
    { name: 'Medusa', size: 'med' },
    { name: 'Mongrelman', size: 'med' },
    { name: 'Morlock', size: 'med' },
    { name: 'Mothman', size: 'med' },
    { name: 'Nightgaunt', size: 'med' },
    { name: 'Onyvolan', size: 'med' },
    { name: 'Popobala', size: 'med' },
    { name: 'Psoglav', size: 'med' },
    { name: 'Qallupilluk', size: 'med' },
    { name: 'Rawhead', size: 'med' },
    { name: 'Rokurokubi', size: 'med' },
    { name: 'Sabosan', size: 'med' },
    { name: 'Sahuagin', size: 'med' },
    { name: 'Sea Hag', size: 'med' },
    { name: 'Selkie', size: 'med' },
    { name: 'Serpentfolk', size: 'med' },
    { name: 'Skum', size: 'med' },
    { name: 'Storm Hag', size: 'med' },
    { name: 'Stygira', size: 'med' },
    { name: 'Tanuki', size: 'med' },
    { name: 'Tenome', size: 'med' },
    { name: 'Thriae Dancer', size: 'med' },
    { name: 'Thriae Seer', size: 'med' },
    { name: 'Thriae Soldier', size: 'med' },
    { name: 'Umasi', size: 'med' },
    { name: 'Vodyanoi', size: 'med' },
    { name: 'Winter Hag', size: 'med' },
    { name: 'Witchwyrd', size: 'med' },
    { name: 'Charda', size: 'sm' },
    { name: 'Kappa', size: 'sm' },
    { name: 'Ningyo', size: 'sm' },
    { name: 'Pukwudgie', size: 'sm' }
];

MorphinOptions.giant = [
    { name: 'Ash Giant', size: 'lg' },
    { name: 'Cliff Giant', size: 'lg' },
    { name: 'Cyclops Grand-Eye', size: 'lg' },
    { name: 'Cyclops Lorekeeper', size: 'lg' },
    { name: 'Desert Giant', size: 'lg' },
    { name: 'Ettin', size: 'lg' },
    { name: 'Firbolg', size: 'lg' },
    { name: 'Fire Giant Doombringer', size: 'lg' },
    { name: 'Fire Giant Glaive', size: 'lg' },
    { name: 'Fire Giant King', size: 'lg' },
    { name: 'Fire Giant Lieutenant', size: 'lg' },
    { name: 'Fire Giant Queen', size: 'lg' },
    { name: 'Freshwater Merrow', size: 'lg' },
    { name: 'Frost Giant Battle Priest', size: 'lg' },
    { name: 'Frost Giant Elite Scout', size: 'lg' },
    { name: 'Frost Giant Hunter', size: 'lg' },
    { name: 'Hill Giant', size: 'lg' },
    { name: 'Kabandha', size: 'lg' },
    { name: 'Marsh Giant', size: 'lg' },
    { name: 'Moss Troll', size: 'lg' },
    { name: 'Ogre', size: 'lg' },
    { name: 'Ogre Boss', size: 'lg' },
    { name: 'Ogre Glutton', size: 'lg' },
    { name: 'Ogre Hunter', size: 'lg' },
    { name: 'Ogre Mancatcher', size: 'lg' },
    { name: 'Ogre Priest', size: 'lg' },
    { name: 'Ogre Stalker', size: 'lg' },
    { name: 'Oracular Cyclops', size: 'lg' },
    { name: 'Shadow Giant', size: 'lg' },
    { name: 'Slag Giant', size: 'lg' },
    { name: 'Stone Giant', size: 'lg' },
    { name: 'Tomb Giant', size: 'lg' },
    { name: 'Troll', size: 'lg' },
    { name: 'Troll Acolyte', size: 'lg' },
    { name: 'Troll Berserker', size: 'lg' },
    { name: 'Troll Elder Matron', size: 'lg' },
    { name: 'Troll Fury', size: 'lg' },
    { name: 'Wood Giant', size: 'lg' },
    { name: 'Athach', size: 'huge' },
    { name: 'Cloud Giant', size: 'huge' },
    { name: 'Great Cyclops', size: 'huge' },
    { name: 'Inverted Giant', size: 'huge' },
    { name: 'Jotund Troll', size: 'huge' },
    { name: 'Jungle Giant', size: 'huge' },
    { name: 'Moon Giant', size: 'huge' },
    { name: 'Mountain Troll', size: 'huge' },
    { name: 'Ocean Giant', size: 'huge' },
    { name: 'Papinijuwari', size: 'huge' },
    { name: 'Plague Giant', size: 'huge' },
    { name: 'Saltwater Merrow', size: 'huge' },
    { name: 'Savage Great Cyclops', size: 'huge' },
    { name: 'Storm Giant', size: 'huge' },
    { name: 'Sun Giant', size: 'huge' },
    { name: 'Taiga Giant', size: 'huge' }
];

MorphinOptions.humanoid = [];

MorphinOptions.swarm = [];

MorphinOptions.vermin = [
    { name: 'Belostomatid', size: 'lg' },
    { name: 'Blood Caterpillar', size: 'lg' },
    { name: 'Bluetip Eurypterid', size: 'lg' },
    { name: 'Giant Ant Lion', size: 'lg' },
    { name: 'Giant Black Widow', size: 'lg' },
    { name: 'Giant Hellgrammite', size: 'lg' },
    { name: 'Giant Jellyfish', size: 'lg' },
    { name: 'Giant Mantis', size: 'lg' },
    { name: 'Giant Queen Bee', size: 'lg' },
    { name: 'Giant Scorpion', size: 'lg' },
    { name: 'Giant Sea Anemone', size: 'lg' },
    { name: 'Giant Spear Urchin', size: 'lg' },
    { name: 'Giant Stag Beetle', size: 'lg' },
    { name: 'Giant Starfish', size: 'lg' },
    { name: 'Giant Wasp', size: 'lg' },
    { name: 'Giant Water Strider', size: 'lg' },
    { name: 'Knight Ant', size: 'lg' },
    { name: 'Mammoth Flea', size: 'lg' },
    { name: 'Scarab Beetle', size: 'lg' },
    { name: 'Slicer Beetle', size: 'lg' },
    { name: 'Albino Cave Solifugid', size: 'med' },
    { name: 'Cave Fisher', size: 'med' },
    { name: 'Cave Scorpion', size: 'med' },
    { name: 'Coffin Anemone', size: 'med' },
    { name: 'Common Eurypterid', size: 'med' },
    { name: 'Crimson Jellyfish', size: 'med' },
    { name: 'Giant Ant', size: 'med' },
    { name: 'Giant Bee', size: 'med' },
    { name: 'Giant Centipede', size: 'med' },
    { name: 'Giant Crab', size: 'med' },
    { name: 'Giant Dragonfly', size: 'med' },
    { name: 'Giant Fly', size: 'med' },
    { name: 'Giant Leech', size: 'med' },
    { name: 'Giant Locust', size: 'med' },
    { name: 'Giant Maggot', size: 'med' },
    { name: 'Giant Mantis Shrimp', size: 'med' },
    { name: 'Giant Mosquito', size: 'med' },
    { name: 'Giant Spider', size: 'med' },
    { name: 'Giant Termite', size: 'med' },
    { name: 'Giant Tube Worm', size: 'med' },
    { name: 'Great Assassin Bug', size: 'med' },
    { name: 'Great Diadem Urchin', size: 'med' },
    { name: 'Giant Hunter Urchin', size: 'med' },
    { name: 'Horn Caterpillar', size: 'med' },
    { name: 'Stalk Beetle', size: 'med' },
    { name: 'Xenopterid', size: 'med' },
    { name: 'Death\'s Head Jellyfish', size: 'sm' },
    { name: 'Fire Beetle', size: 'sm' },
    { name: 'Ghost Scorpion', size: 'sm' },
    { name: 'Giant Assassin Bug', size: 'sm' },
    { name: 'Giant Cockroach', size: 'sm' },
    { name: 'Giant Crab Spider', size: 'sm' },
    { name: 'Giant Flea', size: 'sm' },
    { name: 'Giant Dragonfly Nymph', size: 'sm' },
    { name: 'Giant Rot Grub', size: 'sm' },
    { name: 'Giant Solifugid', size: 'sm' },
    { name: 'Giant Tick', size: 'sm' },
    { name: 'Nymph Water Strider', size: 'sm' },
    { name: 'Ochre Eurypterid', size: 'sm' },
    { name: 'Giant Botfly', size: 'tiny' },
    { name: 'Giant Isopod', size: 'tiny' },
    { name: 'Greensting Scorpion', size: 'tiny' },
    { name: 'House Centipede', size: 'tiny' },
    { name: 'King Crab', size: 'tiny' },
    { name: 'Scarlet Spider', size: 'tiny' }
];

MorphinOptions.magicalBeast = [
    { name: 'Agyra', size: 'col' },
    { name: 'Aspidochelone', size: 'col' },
    { name: 'Behemoth, Ravener', size: 'col' },
    { name: 'Bezravnis', size: 'col' },
    { name: 'Bhole', size: 'col' },
    { name: 'Faceless Whale', size: 'col' },
    { name: 'Festering Ulunat, The Unholy First', size: 'col' },
    { name: 'Fire Whale', size: 'col' },
    { name: 'Julunggali', size: 'col' },
    { name: 'Mogaru', size: 'col' },
    { name: 'Oma', size: 'col' },
    { name: 'Ouroboros', size: 'col' },
    { name: 'Tarrasque', size: 'col' },
    { name: 'Tempest Behemoth', size: 'col' },
    { name: 'Thalassic Behemoth', size: 'col' },
    { name: 'Thunder Behemoth', size: 'col' },
    { name: 'Ugash-Iram', size: 'col' },
    { name: 'Varklops', size: 'col' },
    { name: 'Yarthoon', size: 'col' },
    { name: 'Pipefox', size: 'dim' },
    { name: 'Locust Plague Swarm', size: 'fine' },
    { name: 'Addu', size: 'grg' },
    { name: 'Atuikakura', size: 'grg' },
    { name: 'Bandersnatch', size: 'grg' },
    { name: 'Cipactli', size: 'grg' },
    { name: 'Deep Sea Serpent', size: 'grg' },
    { name: 'Elder Sphinx', size: 'grg' },
    { name: 'Grootslang', size: 'grg' },
    { name: 'Hunting Horror', size: 'grg' },
    { name: 'Inkanyamba', size: 'grg' },
    { name: 'Isonade', size: 'grg' },
    { name: 'Ketesthius', size: 'grg' },
    { name: 'Kraken', size: 'grg' },
    { name: 'Lusca', size: 'grg' },
    { name: 'Ophiotaurus', size: 'grg' },
    { name: 'Purple Worm', size: 'grg' },
    { name: 'Rukh', size: 'grg' },
    { name: 'Sea Serpent', size: 'grg' },
    { name: 'Simurgh', size: 'grg' },
    { name: 'Thunderbird', size: 'grg' },
    { name: 'Abaia', size: 'huge' },
    { name: 'Akhlut', size: 'huge' },
    { name: 'Amarok', size: 'huge' },
    { name: 'Ankhrav', size: 'huge' },
    { name: 'Behir', size: 'huge' },
    { name: 'Bolla', size: 'huge' },
    { name: 'Bulette', size: 'huge' },
    { name: 'Cherufe', size: 'huge' },
    { name: 'Corbayrant', size: 'huge' },
    { name: 'Estuarine Worm (Ahket)', size: 'huge' },
    { name: 'Feeder in the Depths', size: 'huge' },
    { name: 'Feranth', size: 'huge' },
    { name: 'Frost Worm', size: 'huge' },
    { name: 'Furcifer', size: 'huge' },
    { name: 'Gargiya', size: 'huge' },
    { name: 'Giant Owl', size: 'huge' },
    { name: 'Gigas Clam', size: 'huge' },
    { name: 'Grisantian Lion', size: 'huge' },
    { name: 'Hungerer', size: 'huge' },
    { name: 'Hydra', size: 'huge' },
    { name: 'Jubjub Bird', size: 'huge' },
    { name: 'Juggernaut Beetle', size: 'huge' },
    { name: 'Kokogiak', size: 'huge' },
    { name: 'Legendary Chimera', size: 'huge' },
    { name: 'Leng Spider', size: 'huge' },
    { name: 'Lukwata', size: 'huge' },
    { name: 'Makara Vahana', size: 'huge' },
    { name: 'Mapinguari', size: 'huge' },
    { name: 'Mobogo', size: 'huge' },
    { name: 'Myrmecoleon', size: 'huge' },
    { name: 'Remorhaz', size: 'huge' },
    { name: 'Seps', size: 'huge' },
    { name: 'Shantak', size: 'huge' },
    { name: 'Skrimsl', size: 'huge' },
    { name: 'Star Monarch', size: 'huge' },
    { name: 'Steam Hog', size: 'huge' },
    { name: 'Storm Aurochs', size: 'huge' },
    { name: 'Thrasfyr', size: 'huge' },
    { name: 'Ursikka', size: 'huge' },
    { name: 'Veldenar', size: 'huge' },
    { name: 'Vorvorak', size: 'huge' },
    { name: 'Water Orm', size: 'huge' },
    { name: 'Xanthos', size: 'huge' },
    { name: 'Yaoguai', size: 'huge' },
    { name: 'Ypotryll', size: 'huge' },
    { name: 'Yrthak', size: 'huge' },
    { name: 'Ahool', size: 'lg' },
    { name: 'Ahuizotl', size: 'lg' },
    { name: 'Amphisbaena', size: 'lg' },
    { name: 'Androsphinx', size: 'lg' },
    { name: 'Ankheg', size: 'lg' },
    { name: 'Black Shuck', size: 'lg' },
    { name: 'Burstigeit', size: 'lg' },
    { name: 'Camulatz', size: 'lg' },
    { name: 'Catoblepas', size: 'lg' },
    { name: 'Cerynitis', size: 'lg' },
    { name: 'Chemosit', size: 'lg' },
    { name: 'Chimera', size: 'lg' },
    { name: 'Criosphinx', size: 'lg' },
    { name: 'Cytillipede', size: 'lg' },
    { name: 'Death Dog', size: 'lg' },
    { name: 'Death Worm', size: 'lg' },
    { name: 'Devilfish', size: 'lg' },
    { name: 'Disenchanter', size: 'lg' },
    { name: 'Dragon Horse', size: 'lg' },
    { name: 'Dragonne', size: 'lg' },
    { name: 'Estuarine Worm (Shemu)', size: 'lg' },
    { name: 'Flail Snail', size: 'lg' },
    { name: 'Gammenore', size: 'lg' },
    { name: 'Genghryl', size: 'lg' },
    { name: 'Giant Eagle', size: 'lg' },
    { name: 'Giant Muckdweller', size: 'lg' },
    { name: 'Girallon', size: 'lg' },
    { name: 'Glacier Toad', size: 'lg' },
    { name: 'Gnoph-Keh', size: 'lg' },
    { name: 'Goezspall', size: 'lg' },
    { name: 'Goldpebble', size: 'lg' },
    { name: 'Gorgon', size: 'lg' },
    { name: 'Gray Render', size: 'lg' },
    { name: 'Griffon', size: 'lg' },
    { name: 'Gynosphinx', size: 'lg' },
    { name: 'Hieracosphinx', size: 'lg' },
    { name: 'Hippocampus', size: 'lg' },
    { name: 'Hippogriff', size: 'lg' },
    { name: 'Hodag', size: 'lg' },
    { name: 'Juvenile Rukh', size: 'lg' },
    { name: 'Kamadan', size: 'lg' },
    { name: 'Karkadann', size: 'lg' },
    { name: 'Kirin', size: 'lg' },
    { name: 'Kravyad', size: 'lg' },
    { name: 'Lammasu', size: 'lg' },
    { name: 'Leucrotta', size: 'lg' },
    { name: 'Lion Alebrije', size: 'lg' },
    { name: 'Man-Eating Aurochs', size: 'lg' },
    { name: 'Manticore', size: 'lg' },
    { name: 'Mirror Serpent', size: 'lg' },
    { name: 'Mngwa', size: 'lg' },
    { name: 'Mobat', size: 'lg' },
    { name: 'Muhuru', size: 'lg' },
    { name: 'Nue', size: 'lg' },
    { name: 'Owlbear', size: 'lg' },
    { name: 'Pegasus', size: 'lg' },
    { name: 'Phase Spider', size: 'lg' },
    { name: 'Pyropiscis', size: 'lg' },
    { name: 'Sea Cat', size: 'lg' },
    { name: 'Seaweed Siren', size: 'lg' },
    { name: 'Shalkeshka', size: 'lg' },
    { name: 'Shedu', size: 'lg' },
    { name: 'Skrik Nettle', size: 'lg' },
    { name: 'Sleipnir', size: 'lg' },
    { name: 'Spider Eater', size: 'lg' },
    { name: 'Stymphalidies', size: 'lg' },
    { name: 'Taniwha', size: 'lg' },
    { name: 'Tetrolimulus', size: 'lg' },
    { name: 'Tizheruk', size: 'lg' },
    { name: 'Unicorn', size: 'lg' },
    { name: 'Water Wraith', size: 'lg' },
    { name: 'Winter Wolf', size: 'lg' },
    { name: 'Aranea', size: 'med' },
    { name: 'Baku', size: 'med' },
    { name: 'Basilisk', size: 'med' },
    { name: 'Blink Dog', size: 'med' },
    { name: 'Boreal Wolf', size: 'med' },
    { name: 'Bunyip', size: 'med' },
    { name: 'Delgeth', size: 'med' },
    { name: 'Dweomercat', size: 'med' },
    { name: 'Galvo', size: 'med' },
    { name: 'Grodair', size: 'med' },
    { name: 'Jackalwere', size: 'med' },
    { name: 'Juvenile Seps', size: 'med' },
    { name: 'Kaicharek', size: 'med' },
    { name: 'Krenshar', size: 'med' },
    { name: 'Nekomata', size: 'med' },
    { name: 'Pard', size: 'med' },
    { name: 'Peryton', size: 'med' },
    { name: 'Peuchen', size: 'med' },
    { name: 'Ramidreju', size: 'med' },
    { name: 'Serpopard', size: 'med' },
    { name: 'Sha', size: 'med' },
    { name: 'Siren', size: 'med' },
    { name: 'Skeltercat', size: 'med' },
    { name: 'Slurk', size: 'med' },
    { name: 'Su', size: 'med' },
    { name: 'Thrushmoor Angler', size: 'med' },
    { name: 'Trollhound', size: 'med' },
    { name: 'Uraeus', size: 'med' },
    { name: 'Worg', size: 'med' },
    { name: 'Almiraj', size: 'sm' },
    { name: 'Aurumvorax', size: 'sm' },
    { name: 'Blindheim', size: 'sm' },
    { name: 'Chupacabra', size: 'sm' },
    { name: 'Clawbat', size: 'sm' },
    { name: 'Cockatrice', size: 'sm' },
    { name: 'Darkmantle', size: 'sm' },
    { name: 'Echeneis', size: 'sm' },
    { name: 'Greater Witchcrow', size: 'sm' },
    { name: 'Gryph', size: 'sm' },
    { name: 'Hallowed Lynx', size: 'sm' },
    { name: 'Muckdweller', size: 'sm' },
    { name: 'Rat King', size: 'sm' },
    { name: 'Shasalqu', size: 'sm' },
    { name: 'Shocker Lizard', size: 'sm' },
    { name: 'Voonith', size: 'sm' },
    { name: 'Water Leaper', size: 'sm' },
    { name: 'Witchcrow', size: 'sm' },
    { name: 'Black Spot', size: 'tiny' },
    { name: 'Brain Mole', size: 'tiny' },
    { name: 'Brain Mole Monarch', size: 'tiny' },
    { name: 'Carbuncle', size: 'tiny' },
    { name: 'Ceru', size: 'tiny' },
    { name: 'Chuspiki', size: 'tiny' },
    { name: 'Coral Capuchin', size: 'tiny' },
    { name: 'Cyphergull', size: 'tiny' },
    { name: 'Dweomercat Cub', size: 'tiny' },
    { name: 'Galluvix', size: 'tiny' },
    { name: 'Nehushtan', size: 'tiny' },
    { name: 'Ostovite', size: 'tiny' },
    { name: 'Ratling', size: 'tiny' },
    { name: 'Sin Seeker', size: 'tiny' },
    { name: 'Skvader', size: 'tiny' },
    { name: 'Stirge', size: 'tiny' },
    { name: 'Sun Falcon', size: 'tiny' },
    { name: 'Wolpertinger', size: 'tiny' },
    { name: 'Xiao', size: 'tiny' },
    { name: 'Zoog', size: 'tiny' }
];

MorphinOptions.shifterWildShape = [
    { name: 'Bat', realName: 'Dire Bat', source: 'beastShape', size: 'lg' },
    { name: 'Bear', realName: 'Dire Bear', source: 'beastShape', size: 'lg' },
    { name: 'Boar', realName: 'Dire Boar', source: 'beastShape', size: 'lg' },
    { name: 'Bull', realName: 'Aurochs', source: 'beastShape', size: 'lg' },
    { name: 'Crocodile', realName: 'Crocodile', source: 'beastShape', size: 'lg' },
    { name: 'Deinonychus', realName: 'Deinonychus', source: 'beastShape', size: 'med' },
    { name: 'Dolphin', realName: 'Dolphin', source: 'beastShape', size: 'lg' },
    { name: 'Dragonfly', realName: 'Large Dragonfly', source: 'verminShape', size: 'med' },
    { name: 'Electric Eel', realName: 'Electric Eel', source: 'beastShape', size: 'sm' },
    { name: 'Elephant', realName: 'Elephant', source: 'beastShape', size: 'lg' },
    { name: 'Falcon', realName: 'Falcon', source: 'beastShape', size: 'sm' },
    { name: 'Frog', realName: 'Giant Frog', source: 'beastShape', size: 'lg' },
    { name: 'Giant Wasp', realName: 'Giant Wasp', source: 'verminShape', size: 'lg' },
    { name: 'Horse', realName: 'Horse', source: 'beastShape', size: 'lg' },
    { name: 'Lion', realName: 'Dire Lion', source: 'beastShape', size: 'lg' },
    { name: 'Lizard', realName: 'Giant Frilled Lizard', source: 'beastShape', size: 'lg' },
    { name: 'Mantis', realName: 'Giant Mantis', source: 'beastShape', size: 'lg' },
    { name: 'Monkey', realName: 'Dire Ape', source: 'beastShape', size: 'lg' },
    { name: 'Mouse', realName: 'Dire Rat', source: 'beastShape', size: 'tiny' },
    { name: 'Octopus', realName: 'Octopus', source: 'beastShape', size: 'sm' },
    { name: 'Owl', realName: 'Owl', source: 'beastShape', size: 'med' },
    { name: 'Peafowl', realName: 'Peafowl', source: 'beastShape', size: 'sm' },
    { name: 'Scorpion', realName: 'Giant Scorpion', source: 'verminShape', size: 'lg' },
    { name: 'Snake', realName: 'Emperor Cobra', source: 'beastShape', size: 'lg' },
    { name: 'Snapping Turtle', realName: 'Giant Snapping Turtle', source: 'beastShape', size: 'lg' },
    { name: 'Spider', realName: 'Giant Spider', source: 'verminShape', size: 'med' },
    { name: 'Stag', realName: 'Stag', source: 'beastShape', size: 'lg' },
    { name: 'Tiger', realName: 'Dire Tiger', source: 'beastShape', size: 'lg' },
    { name: 'Wolf', realName: 'Dire Wolf', source: 'beastShape', size: 'lg' },
    { name: 'Wolverine', realName: 'Dire Wolverine', source: 'beastShape', size: 'lg' }
];